name: github_client
description: Dina ios/android exercise.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  chopper: ^4.0.4
  flutter:
    sdk: flutter
  flutter_clean_architecture: ^5.0.0
  json_annotation: ^4.4.0
  
  logging: ^1.0.2
  mockito: ^5.0.17
  shimmer: ^2.0.0
  infinite_scroll_pagination: ^3.0.0
  rxdart: ^0.26.0
  auto_size_text: ^3.0.0
  marquee: ^2.2.0
  
dev_dependencies:
  build_runner: ^2.1.7
  chopper_generator: ^4.0.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3


flutter:
  assets:
    - assets/

  uses-material-design: true
