name: github_client
description: Dina ios/android exercise.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clean_architecture: ^5.0.0
  mockito: ^5.0.17
  very_good_analysis: ^2.4.0


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
